# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /cygdrive/e/src/github/tls-sig-api-v2-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /cygdrive/e/src/github/tls-sig-api-v2-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake.exe -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake.exe -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/e/src/github/tls-sig-api-v2-cpp/CMakeFiles /cygdrive/e/src/github/tls-sig-api-v2-cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/e/src/github/tls-sig-api-v2-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tlssigapi_v2_tool

# Build rule for target.
tlssigapi_v2_tool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tlssigapi_v2_tool
.PHONY : tlssigapi_v2_tool

# fast build rule for target.
tlssigapi_v2_tool/fast:
	$(MAKE) -f CMakeFiles/tlssigapi_v2_tool.dir/build.make CMakeFiles/tlssigapi_v2_tool.dir/build
.PHONY : tlssigapi_v2_tool/fast

#=============================================================================
# Target rules for targets named tlssigapi_v2

# Build rule for target.
tlssigapi_v2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tlssigapi_v2
.PHONY : tlssigapi_v2

# fast build rule for target.
tlssigapi_v2/fast:
	$(MAKE) -f CMakeFiles/tlssigapi_v2.dir/build.make CMakeFiles/tlssigapi_v2.dir/build
.PHONY : tlssigapi_v2/fast

src/opensslthreadlock.o: src/opensslthreadlock.cpp.o

.PHONY : src/opensslthreadlock.o

# target to build an object file
src/opensslthreadlock.cpp.o:
	$(MAKE) -f CMakeFiles/tlssigapi_v2.dir/build.make CMakeFiles/tlssigapi_v2.dir/src/opensslthreadlock.cpp.o
.PHONY : src/opensslthreadlock.cpp.o

src/opensslthreadlock.i: src/opensslthreadlock.cpp.i

.PHONY : src/opensslthreadlock.i

# target to preprocess a source file
src/opensslthreadlock.cpp.i:
	$(MAKE) -f CMakeFiles/tlssigapi_v2.dir/build.make CMakeFiles/tlssigapi_v2.dir/src/opensslthreadlock.cpp.i
.PHONY : src/opensslthreadlock.cpp.i

src/opensslthreadlock.s: src/opensslthreadlock.cpp.s

.PHONY : src/opensslthreadlock.s

# target to generate assembly for a file
src/opensslthreadlock.cpp.s:
	$(MAKE) -f CMakeFiles/tlssigapi_v2.dir/build.make CMakeFiles/tlssigapi_v2.dir/src/opensslthreadlock.cpp.s
.PHONY : src/opensslthreadlock.cpp.s

src/tls_sig_api_v2.o: src/tls_sig_api_v2.cpp.o

.PHONY : src/tls_sig_api_v2.o

# target to build an object file
src/tls_sig_api_v2.cpp.o:
	$(MAKE) -f CMakeFiles/tlssigapi_v2.dir/build.make CMakeFiles/tlssigapi_v2.dir/src/tls_sig_api_v2.cpp.o
.PHONY : src/tls_sig_api_v2.cpp.o

src/tls_sig_api_v2.i: src/tls_sig_api_v2.cpp.i

.PHONY : src/tls_sig_api_v2.i

# target to preprocess a source file
src/tls_sig_api_v2.cpp.i:
	$(MAKE) -f CMakeFiles/tlssigapi_v2.dir/build.make CMakeFiles/tlssigapi_v2.dir/src/tls_sig_api_v2.cpp.i
.PHONY : src/tls_sig_api_v2.cpp.i

src/tls_sig_api_v2.s: src/tls_sig_api_v2.cpp.s

.PHONY : src/tls_sig_api_v2.s

# target to generate assembly for a file
src/tls_sig_api_v2.cpp.s:
	$(MAKE) -f CMakeFiles/tlssigapi_v2.dir/build.make CMakeFiles/tlssigapi_v2.dir/src/tls_sig_api_v2.cpp.s
.PHONY : src/tls_sig_api_v2.cpp.s

src/tlssigapi_v2_tool.o: src/tlssigapi_v2_tool.cpp.o

.PHONY : src/tlssigapi_v2_tool.o

# target to build an object file
src/tlssigapi_v2_tool.cpp.o:
	$(MAKE) -f CMakeFiles/tlssigapi_v2_tool.dir/build.make CMakeFiles/tlssigapi_v2_tool.dir/src/tlssigapi_v2_tool.cpp.o
.PHONY : src/tlssigapi_v2_tool.cpp.o

src/tlssigapi_v2_tool.i: src/tlssigapi_v2_tool.cpp.i

.PHONY : src/tlssigapi_v2_tool.i

# target to preprocess a source file
src/tlssigapi_v2_tool.cpp.i:
	$(MAKE) -f CMakeFiles/tlssigapi_v2_tool.dir/build.make CMakeFiles/tlssigapi_v2_tool.dir/src/tlssigapi_v2_tool.cpp.i
.PHONY : src/tlssigapi_v2_tool.cpp.i

src/tlssigapi_v2_tool.s: src/tlssigapi_v2_tool.cpp.s

.PHONY : src/tlssigapi_v2_tool.s

# target to generate assembly for a file
src/tlssigapi_v2_tool.cpp.s:
	$(MAKE) -f CMakeFiles/tlssigapi_v2_tool.dir/build.make CMakeFiles/tlssigapi_v2_tool.dir/src/tlssigapi_v2_tool.cpp.s
.PHONY : src/tlssigapi_v2_tool.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... tlssigapi_v2_tool"
	@echo "... rebuild_cache"
	@echo "... tlssigapi_v2"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... install/strip"
	@echo "... install"
	@echo "... src/opensslthreadlock.o"
	@echo "... src/opensslthreadlock.i"
	@echo "... src/opensslthreadlock.s"
	@echo "... src/tls_sig_api_v2.o"
	@echo "... src/tls_sig_api_v2.i"
	@echo "... src/tls_sig_api_v2.s"
	@echo "... src/tlssigapi_v2_tool.o"
	@echo "... src/tlssigapi_v2_tool.i"
	@echo "... src/tlssigapi_v2_tool.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

